# Generated by Django 4.2.11 on 2024-03-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0001_initial"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="bicycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bicycles.bicycle"
            ),
        ),
    ]
