# Generated by Django 4.2.11 on 2024-03-18 13:51

import CycleShop.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="product_images/",
                validators=[
                    CycleShop.core.validators.MaxFileSizeValidator(limit_value=5242880)
                ],
            ),
        ),
    ]
