# Generated by Django 4.2.11 on 2024-03-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0001_initial"),
        ("images", "0002_alter_productimage_bicycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="bicycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="bicycles.bicycle",
            ),
        ),
    ]
