# Generated by Django 4.2.11 on 2024-03-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0001_initial"),
        ("bicycles", "0001_initial"),
        ("equipment", "0001_initial"),
        ("components", "0001_initial"),
        ("images", "0003_alter_productimage_bicycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="accessories.accessories",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="components",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="components.components",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="equipment.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="bicycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="bicycles.bicycle",
            ),
        ),
    ]
