# Generated by Django 4.2.11 on 2024-03-16 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Components",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cassettes", "Cassettes"),
                            ("Chains", "Chains"),
                            ("Forks", "Forks"),
                            ("Tubeless Tyres", "Tubeless Tyres"),
                            ("Inner Tubes", "Inner Tubes"),
                            ("Hubs", "Hubs"),
                            ("Rear Shock Absorbers", "Rear Shock Absorbers"),
                            ("Rear Derailleurs", "Rear Derailleurs"),
                            ("Spokes", "Spokes"),
                            ("Seatpost Clamps", "Seatpost Clamps"),
                            ("Shifters", "Shifters"),
                            ("Handlebars", "Handlebars"),
                            ("Cranks", "Cranks"),
                            ("Pedals", "Pedals"),
                            ("Front Derailleur", "Front Derailleur"),
                            ("Saddles", "Saddles"),
                            ("Brakes", "Brakes"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components_inventory",
                        to="components.components",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentsImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="components_images/")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_images",
                        to="components.components",
                    ),
                ),
            ],
        ),
    ]
