# Generated by Django 4.2.11 on 2024-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="components",
            name="installation_type",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="components",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="components",
            name="speed_compatibility",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
