# Generated by Django 4.2.11 on 2024-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_components_quantity_delete_componentsinventory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComponentsImages",
        ),
    ]
