# Generated by Django 4.2.11 on 2024-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_components_installation_type_components_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="components",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
