# Generated by Django 4.2.11 on 2024-03-16 10:36

import CycleShop.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Gloves",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Long Finger Gloves", "Long Finger"),
                            ("Short Finger Gloves", "Short Finger"),
                            ("Winter Gloves", "Winter Gloves"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Goggles",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sunglasses", "Sunglasses"),
                            ("Safety Goggles", "Safety Goggles"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Helmet",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mountain", "Mountain"),
                            ("Mountain Full Face", "Mountain Full Face"),
                            ("Road", "Road"),
                            ("Urban", "Urban"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Protection",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Knee Pads", "Knee Pads"),
                            ("Elbow Pads", "Elbow Pads"),
                            ("Neck Protectors", "Neck Protectors"),
                            ("Body Protectors", "Body Protectors"),
                            ("Protectors Set", "Set Protectors"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="EquipmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment_images/",
                        validators=[
                            CycleShop.core.validators.MaxFileSizeValidator(
                                limit_value=5242880
                            )
                        ],
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_images",
                        to="equipment.equipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Size S"),
                            ("M", "Size M"),
                            ("L", "Size L"),
                            ("XL", "Size Xl"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_inventory",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "unique_together": {("equipment", "size")},
            },
        ),
    ]
