# Generated by Django 4.2.11 on 2024-03-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Size S"),
                            ("M", "Size M"),
                            ("L", "Size L"),
                            ("XL", "Size Xl"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Gloves",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "material_palm",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "material_back",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "padding_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "grip_enhancing_features",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "closure_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "waterproof",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("touchscreen_compatible", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Long Finger Gloves", "Long Finger"),
                            ("Short Finger Gloves", "Short Finger"),
                            ("Winter Gloves", "Winter Gloves"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Goggles",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "UV_protection_level",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "lens_material",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "frame_material",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "polarized_lenses",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("anti_fog", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Sunglasses", "Sunglasses"),
                            ("Safety Goggles", "Safety Goggles"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Helmet",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("construction_type", models.CharField(max_length=15)),
                (
                    "retention_system",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "safety_certification",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("weight", models.DecimalField(decimal_places=3, max_digits=5)),
                ("adjustable_visor", models.BooleanField(default=False)),
                ("MIPS_technology", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mountain", "Mountain"),
                            ("Mountain Full Face", "Mountain Full Face"),
                            ("Road", "Road"),
                            ("Urban", "Urban"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
        migrations.CreateModel(
            name="Protection",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=20, null=True)),
                ("impact_resistance_rating", models.PositiveIntegerField(default=1)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=5)),
                ("adjustability", models.BooleanField(default=True)),
                ("ventilation", models.BooleanField(default=True)),
                ("washable", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Knee Pads", "Knee Pads"),
                            ("Elbow Pads", "Elbow Pads"),
                            ("Neck Protectors", "Neck Protectors"),
                            ("Body Protectors", "Body Protectors"),
                            ("Protectors Set", "Set Protectors"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            bases=("equipment.equipment",),
        ),
    ]
