# Generated by Django 4.2.11 on 2024-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="size",
            field=models.CharField(
                choices=[
                    ("S", "Size S"),
                    ("M", "Size M"),
                    ("L", "Size L"),
                    ("XL", "Size Xl"),
                ],
                default="M",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gloves",
            name="CLOSURE_TYPE",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="gloves",
            name="GRIP_ENHANCING_FEATURES",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gloves",
            name="MATERIAL_BACK",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="gloves",
            name="MATERIAL_PALM",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="gloves",
            name="PADDING_TYPE",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gloves",
            name="TOUCHSCREEN_COMPATIBLE",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gloves",
            name="WATERPROOF",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="goggles",
            name="ANTI_FOG",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="goggles",
            name="FRAME_MATERIAL",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="goggles",
            name="LENS_MATERIAL",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="goggles",
            name="POLARIZED_LENSES",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="goggles",
            name="UV_PROTECTION_LEVEL",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="helmet",
            name="ADJUSTABLE_VISOR",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="helmet",
            name="CONSTRUCTION_TYPE",
            field=models.CharField(default="asdasd", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="helmet",
            name="MIPS_TECHNOLOGY",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="helmet",
            name="RETENTION_SYSTEM",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="helmet",
            name="SAFETY_CERTIFICATION",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="helmet",
            name="WEIGHT",
            field=models.DecimalField(decimal_places=3, default=23, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="protection",
            name="ADJUSTABILITY",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="protection",
            name="IMPACT_RESISTANCE_RATING",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="protection",
            name="MATERIAL",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="protection",
            name="VENTILATION",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="protection",
            name="WASHABLE",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="protection",
            name="WEIGHT",
            field=models.DecimalField(decimal_places=3, default=34, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goggles",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sunglasses", "Sunglasses"),
                    ("Safety Goggles", "Safety Goggles"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="EquipmentInventory",
        ),
    ]
