# Generated by Django 4.2.11 on 2024-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_equipment_size_alter_gloves_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gloves",
            name="closure_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="gloves",
            name="grip_enhancing_features",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="gloves",
            name="material_back",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="gloves",
            name="material_palm",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="gloves",
            name="padding_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="goggles",
            name="frame_material",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="goggles",
            name="lens_material",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="helmet",
            name="construction_type",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="helmet",
            name="retention_system",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="helmet",
            name="safety_certification",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="protection",
            name="material",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
