# Generated by Django 4.2.11 on 2024-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_equipment_quantity_equipment_size_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EquipmentImage",
        ),
    ]
