# Generated by Django 4.2.11 on 2024-03-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("frame", models.CharField(max_length=100)),
                ("fork", models.CharField(blank=True, max_length=100, null=True)),
                ("brakes", models.CharField(max_length=100)),
                ("gears", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tyres_size",
                    models.CharField(
                        choices=[
                            ("26", "Size Twenty Six"),
                            ("27.5", "Size Twenty Seven"),
                            ("29", "Size Twenty Nine"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ElectricBicycle",
            fields=[
                (
                    "bicycle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bicycles.bicycle",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electric mountain", "Electric Mountain"),
                            ("Electric city", "Electric City"),
                            ("Electric kids", "Electric Kids"),
                            ("Electric road", "Electric Road"),
                        ],
                        max_length=30,
                    ),
                ),
                ("engine", models.CharField(max_length=50)),
                ("battery", models.CharField(max_length=50)),
                ("display", models.CharField(max_length=50)),
                ("charger", models.CharField(max_length=50)),
            ],
            bases=("bicycles.bicycle",),
        ),
        migrations.CreateModel(
            name="MountainBicycle",
            fields=[
                (
                    "bicycle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bicycles.bicycle",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hard Trail", "Hard Trail"),
                            ("Full Suspension", "Full Suspension"),
                            ("Fat Bike", "Fat Bike"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            bases=("bicycles.bicycle",),
        ),
        migrations.CreateModel(
            name="RoadBicycle",
            fields=[
                (
                    "bicycle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bicycles.bicycle",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Gravel", "Gravel Bikes"),
                            ("Cyclocross", "Cyclocross Bikes"),
                            ("Fixie", "Fixie"),
                            ("Triathlon", "Triathlon"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            bases=("bicycles.bicycle",),
        ),
        migrations.CreateModel(
            name="BicycleInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "bicycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bicycles.bicycle",
                    ),
                ),
            ],
        ),
    ]
