# Generated by Django 4.2.11 on 2024-03-13 21:31

import CycleShop.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BicycleSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Size S"),
                            ("M", "Size M"),
                            ("L", "Size L"),
                            ("XL", "Size Xl"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectricBicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("frame", models.CharField(max_length=100)),
                ("fork", models.CharField(blank=True, max_length=100, null=True)),
                ("brakes", models.CharField(max_length=100)),
                ("gears", models.CharField(blank=True, max_length=100, null=True)),
                ("tires", models.CharField(max_length=100)),
                ("fork_travel", models.PositiveIntegerField(blank=True, null=True)),
                ("frame_travel", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electric mountain", "Electric Mountain"),
                            ("Electric city", "Electric City"),
                            ("Electric kids", "Electric Kids"),
                            ("Electric road", "Electric Road"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tyres_size",
                    models.CharField(
                        choices=[
                            ("26", "Size Twenty Six"),
                            ("27.5", "Size Twenty Seven"),
                            ("29", "Size Twenty Nine"),
                        ],
                        max_length=10,
                    ),
                ),
                ("engine", models.CharField(max_length=50)),
                ("battery", models.CharField(max_length=50)),
                ("display", models.CharField(max_length=50)),
                ("charger", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MountainBicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("frame", models.CharField(max_length=100)),
                ("fork", models.CharField(blank=True, max_length=100, null=True)),
                ("brakes", models.CharField(max_length=100)),
                ("gears", models.CharField(blank=True, max_length=100, null=True)),
                ("tires", models.CharField(max_length=100)),
                ("fork_travel", models.PositiveIntegerField(blank=True, null=True)),
                ("frame_travel", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hard Trail", "Hard Trail"),
                            ("Full Suspension", "Full Suspension"),
                            ("Fat Bike", "Fat Bike"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tyres_size",
                    models.CharField(
                        choices=[
                            ("26", "Size Twenty Six"),
                            ("27.5", "Size Twenty Seven"),
                            ("29", "Size Twenty Nine"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoadBicycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("frame", models.CharField(max_length=100)),
                ("fork", models.CharField(blank=True, max_length=100, null=True)),
                ("brakes", models.CharField(max_length=100)),
                ("gears", models.CharField(blank=True, max_length=100, null=True)),
                ("tires", models.CharField(max_length=100)),
                ("fork_travel", models.PositiveIntegerField(blank=True, null=True)),
                ("frame_travel", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Gravel", "Gravel Bikes"),
                            ("Cyclocross", "Cyclocross Bikes"),
                            ("Fixie", "Fixie"),
                            ("Triathlon", "Triathlon"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BicycleInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(blank=True, to="bicycles.bicyclesize"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BicycleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="bicycle_images/",
                        validators=[
                            CycleShop.core.validators.MaxFileSizeValidator(
                                limit_value=5242880
                            )
                        ],
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
