# Generated by Django 4.2.11 on 2024-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bicycle",
            name="size",
            field=models.CharField(
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bicycle",
            name="tyres_size",
            field=models.CharField(
                choices=[("26", "26"), ("27.5", "27.5"), ("29", "29")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="electricbicycle",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electric mountain", "Electric mountain"),
                    ("Electric city", "Electric city"),
                    ("Electric kids", "Electric kids"),
                    ("Electric road", "Electric road"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="roadbicycle",
            name="category",
            field=models.CharField(
                choices=[
                    ("Gravel", "Gravel"),
                    ("Cyclocross", "Cyclocross"),
                    ("Fixie", "Fixie"),
                    ("Triathlon", "Triathlon"),
                ],
                max_length=30,
            ),
        ),
    ]
