# Generated by Django 4.2.11 on 2024-03-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bicycleinventory",
            unique_together={("bicycle", "size")},
        ),
    ]
