# Generated by Django 4.2.11 on 2024-03-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0002_alter_bicycleinventory_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bicycleinventory",
            name="size",
            field=models.CharField(
                choices=[
                    ("S", "Size S"),
                    ("M", "Size M"),
                    ("L", "Size L"),
                    ("XL", "Size Xl"),
                ],
                max_length=10,
            ),
        ),
    ]
