# Generated by Django 4.2.11 on 2024-03-15 11:43

import CycleShop.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0003_alter_bicycleinventory_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="BicycleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bicycle_images/",
                        validators=[
                            CycleShop.core.validators.MaxFileSizeValidator(
                                limit_value=5242880
                            )
                        ],
                    ),
                ),
                (
                    "bicycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="bicycles.bicycle",
                    ),
                ),
            ],
        ),
    ]
