# Generated by Django 4.2.11 on 2024-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0004_bicycleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricbicycle",
            name="max_speed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="electricbicycle",
            name="motor_power",
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mountainbicycle",
            name="dropper_post",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mountainbicycle",
            name="fork_travel",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mountainbicycle",
            name="frame_travel",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mountainbicycle",
            name="suspension_lockout",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mountainbicycle",
            name="tubeless_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roadbicycle",
            name="frame_geometry",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="roadbicycle",
            name="handlebar_type",
            field=models.CharField(
                choices=[("Drop", "Drop"), ("Bullhorn", "Bullhorn"), ("Flat", "Flat")],
                default="Drop",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
