# Generated by Django 4.2.11 on 2024-03-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bicycles", "0005_electricbicycle_max_speed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BicycleImage",
        ),
    ]
