# Generated by Django 4.2.11 on 2024-04-04 13:05

import CycleShop.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_cycleshopuser_groups_cycleshopuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cycleshopuser",
            managers=[
                ("objects", CycleShop.accounts.models.CycleShopUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="cycleshopuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="cycleshopuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
