# Generated by Django 4.2.11 on 2024-04-05 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_cycleshopuser_managers_cycleshopuser_is_active_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("town", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
