# Generated by Django 4.2.11 on 2024-03-16 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Everything",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Equipment", "Equipment"),
                            ("Accessories", "Accessories"),
                            ("Components", "Components"),
                        ],
                        max_length=30,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
