# Generated by Django 4.2.11 on 2024-03-21 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Bike Carriers", "Bike Carriers"),
                            ("Bike Racks", "Bike Racks"),
                            ("Child Bike Seat", "Child Bike Sead"),
                            ("Panniers and Bags", "Panniers And Bags"),
                            ("Bells and Horns", "Bells And Horns"),
                            ("Mudguards", "Mudguards"),
                            ("Locks", "Locks"),
                            ("Baskets", "Baskets"),
                            ("Mirrors", "Mirrors"),
                            ("Pumps", "Pumps"),
                            ("Footpegs", "Footpegs"),
                            ("Phone Holder", "Phone Holder"),
                            ("Frame and Saddle Bags", "Frame And Saddle Gabs"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
