# Generated by Django 4.2.11 on 2024-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="adjustability",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="accessories",
            name="attachment_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="accessories",
            name="capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="accessories",
            name="weather_resistance",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
