# Generated by Django 4.2.11 on 2024-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="everything",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Knee Pads", "Knee Pads"), ("Elbow Pads", "Elbow Pads")],
                max_length=30,
                null=True,
            ),
        ),
    ]
