# Generated by Django 4.2.11 on 2024-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0002_accessories_adjustability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessories",
            name="category",
            field=models.CharField(
                choices=[
                    ("Bike Carriers", "Bike Carriers"),
                    ("Bike Racks", "Bike Racks"),
                    ("Child Bike Seat", "Child Bike Seat"),
                    ("Panniers and Bags", "Panniers and Bags"),
                    ("Bells and Horns", "Bells and Horns"),
                    ("Mudguards", "Mudguards"),
                    ("Locks", "Locks"),
                    ("Baskets", "Baskets"),
                    ("Mirrors", "Mirrors"),
                    ("Pumps", "Pumps"),
                    ("Footpegs", "Footpegs"),
                    ("Phone Holder", "Phone Holder"),
                    ("Frame and Saddle Bags", "Frame and Saddle Bags"),
                ],
                max_length=30,
            ),
        ),
    ]
