# Generated by Django 4.2.11 on 2024-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0002_alter_everything_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="everything",
            old_name="type",
            new_name="type_equipment",
        ),
        migrations.AddField(
            model_name="everything",
            name="type_accessories",
            field=models.CharField(
                blank=True,
                choices=[("Gloves", "Gloves"), ("Helmets", "Helmets")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="everything",
            name="type_components",
            field=models.CharField(
                blank=True,
                choices=[("Cassettes", "Cassettes"), ("Chains", "Chains")],
                max_length=30,
                null=True,
            ),
        ),
    ]
