# Generated by Django 4.2.11 on 2024-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0004_accessories_accessoryimages_delete_everything"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessoryImages",
        ),
    ]
